theme: jekyll-theme-cayman

locale                   : "en-US"
title                    : Minki Lee
title_separator          : "-"
name                     : "Lee Minki"
description              : "Personal Profile and Blog for Research & Development results."
url                      : "https://leeminki02.github.io"
social-links:
    github: leeminki02
plugins:
    - jekyll-sitemap